global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'datt-platform'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['spring-boot-app:8080']

  - job_name: 'wave-messaging'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['wave-messaging-service:8081']

  - job_name: 'lookout-system'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['lookout-api:8080']
